services:
  postgres:
    image: postgres:17.6
    environment:
      POSTGRES_DB: ${PSQL_DB}
      POSTGRES_USER: ${PSQL_USER}
      POSTGRES_PASSWORD: ${PSQL_PASSWORD}
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    restart: always
    networks:
      - odoo-network

  odoo:
    image: odoo:16
    environment:
      - HOST=${PSQL_HOST}
      - USER=${PSQL_USER}
      - PASSWORD=${PSQL_PASSWORD}
      - DB_NAME=${PSQL_DB}
    ports:
      - "8069:8069"
    volumes:
      - ./addons:/mnt/extra-addons
      - ./data/odoo:/var/lib/odoo
    depends_on:
      - postgres
    networks:
      - odoo-network

networks:
  odoo-network:
    driver: bridge